####################################################################################
#                                                                                  #
#  Copyright (c) 2014, 2015 - 2016 Axel Menzel <info@rttr.org>                     #
#                                                                                  #
#  This file is part of RTTR (Run Time Type Reflection)                            #
#  License: MIT License                                                            #
#                                                                                  #
#  Permission is hereby granted, free of charge, to any person obtaining           #
#  a copy of this software and associated documentation files (the "Software"),    #
#  to deal in the Software without restriction, including without limitation       #
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,        #
#  and/or sell copies of the Software, and to permit persons to whom the           #
#  Software is furnished to do so, subject to the following conditions:            #
#                                                                                  #
#  The above copyright notice and this permission notice shall be included in      #
#  all copies or substantial portions of the Software.                             #
#                                                                                  #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      #
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        #
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     #
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          #
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   #
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   #
#  SOFTWARE.                                                                       #
#                                                                                  #
####################################################################################

language: cpp
sudo: false

env:
  global:
    - ARCH_FLAGS_x86='-m32'
    - ARCH_FLAGS_x86_64=''
    - secure: iwgYkkpbrmO5g2MgO1OTt/ljLl1NrFFvjO/2635hLg2MCdz6IlZcEMw/2n4luNofPJYP9xUs2WqAa/n5CtGbYat/Y3MjIgMaH+g491jMAbBS3QPrHLkyOfzJZT8QKZFJ4BQNUYCu9pD2pNwe66D21CkPkWDJmEcWyPFQEs8ReMfik8S1/ZY2FmJmcYRv9/QisBMCaOCBedvrq739GNL8tD8J5O04GEa21R4pZJukVp2DzHRa7wrhjqacDTnnseevXHgFae06sLR6xAeqpWpOaMnZqI8oUso2nKhRnpyNkFj1LXWfYaZRuvNYb8aWq3PyzAwKwVRkvRqb3f8GXFWFVQ5Qow+4VmbCeh9QW2qmAy11UBORs7x+3e+xKo2OalnZvjVakJFDVVvpcw+pfOKov4yuWA3VISREbajVaRI7xOZvI7VgSQ3EiwcNI9ac7ayfjXKbXb5s5Jyqc0s+CB2BFLVHDGhxsiVnu/2EOHahNjylcMi/hWfpn66BjMDS8xxlZicQOzn+QPstBwaUZT9gomfAiRObhttSH+QMdw0u+8lS22D6F1sGD+6/1KhcDPWdZUKH9IrGIg3vYB7ZhlI+KFu3ZzJJXop65ut2t55excXkEIBRaq98sm62MMwBjCTGYPfUi3X0kVQXBHa6u1VBK8o/HcIgOGDt0EjuHwnZgSU=

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386']
      env: COMPILER=g++-4.8 ARCH=x86 CONF=Release UNIT_TESTS=true
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib']
      env: COMPILER=g++-4.8 ARCH=x86_64 CONF=Release UNIT_TESTS=true
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7 ARCH=x86_64 CONF=Release UNIT_TESTS=true
      
    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ ARCH=x86_64 CONF=Release UNIT_TESTS=true CHECK_FORMATTING=true
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386']
      after_success:
        - pip install --user cpp-coveralls
        - coveralls -e 3rd_party -e src/benchmarks -e src/unit_tests -i src/rttr --gcov-options '\-lp' --gcov 'gcov-4.8'
      env: COMPILER=g++-4.8 ARCH=x86 CONF=Debug GCOV_FLAGS='--coverage' UNIT_TESTS=true
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib']
      after_success:
        - pip install --user cpp-coveralls
        - coveralls -e 3rd_party -e src/benchmarks -e src/unit_tests -i src/rttr --gcov-options '\-lp' --gcov 'gcov-4.8'
      env: COMPILER=g++-4.8 ARCH=x86_64 CONF=Debug GCOV_FLAGS='--coverage' UNIT_TESTS=true
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386', 'libc6-dbg:i386', 'valgrind']
      env: COMPILER=g++-4.8 ARCH=x86 CONF=Debug VALGRIND=true UNIT_TESTS=true
      
before_install:
  - export CIT_ROOT=`pwd`
  - cd $CIT_ROOT

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/3rd_party"
  - cd ${DEPS_DIR}
  
  #######################################################################################
  # Install recent CMake
  #######################################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
  - if [[ "${CHECK_FORMATTING}" == "true" ]]; then brew install vera++; fi
    
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - >
      eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" ;
      (cd build && cmake
      -DCMAKE_CXX_COMPILER=${COMPILER}
      -DCMAKE_BUILD_TYPE=${CONF}
      -DCMAKE_CXX_FLAGS="$ARCH_FLAGS $GCOV_FLAGS"
      ..)

script:
  - |
    if [[ "${CHECK_FORMATTING}" == "true" ]]; then
      # F001: Source files should not use the '\r' (CR) character
      # L001: No trailing whitespace at the end of lines
      # L002: Don't use tab characters
      # T001: One-line comments should not have forced continuation
      # T002: Reserved names should not be used for preprocessor macros
      # T009: Comma should not be preceded by whitespace, but should be followed by one
      # T011: Curly brackets from the same pair should be either in the same line or in the same column
      # T013: Source files should contain the copyright notice
      find include -name \*\.h | vera++ --rule F001 --rule L001 --rule L002 -rule T001 -rule T002 -rule T009 -rule T011 -rule T013 --error
    fi
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      # Run unit tests on two cores
      (cd build && make run_tests -j2)
    fi
  - |
    if [[ "${VALGRIND}" == "true" ]]; then
      # Run unit tests on two cores
      (valgrind --leak-check=full --error-exitcode=1 ${TRAVIS_BUILD_DIR}/build/bin/unit_tests_d)
    fi

notifications:
  email:
    - info@rttr.org
