language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" UNIT_TESTS=true
    
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" UNIT_TESTS=true
      
    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" UNIT_TESTS=true
      
  allow_failures:
    - env: COMPILER=clang++-3.7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" UNIT_TESTS=true
    - env: COMPILER=clang++ CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" UNIT_TESTS=true
    
before_install:
  - export CIT_ROOT=`pwd`
  - cd $CIT_ROOT

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/3rd_party"
  - cd ${DEPS_DIR}
  
  #######################################################################################
  # Install recent CMake
  #######################################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
    
before_script:

  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} ${CMAKE_OPTIONS})

script:
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      # Run unit tests on two cores
      (cd build && make run_tests -j2)
    fi
